// Merged & deduplicated quiz data from bai1.txt to bai9.txt
// Note: bai5.txt is identical to bai4.txt and has been removed

const SUBJECTS = {
  bai1: { label: "Pháp Luật ĐC", short: "Bài 1", emoji: "📚" },
  bai2: { label: "Hiến Pháp", short: "Bài 2", emoji: "📜" },
  bai3: { label: "Luật Dân Sự", short: "Bài 3", emoji: "⚖️" },
  bai4: { label: "Luật Hành Chính", short: "Bài 4", emoji: "🏛️" },
  bai6: { label: "Luật Hình Sự", short: "Bài 6", emoji: "🔒" },
  bai7: { label: "Bảo Vệ NTD", short: "Bài 7", emoji: "🛒" },
  bai8: { label: "Phòng Chống TN", short: "Bài 8", emoji: "🚫" },
  bai9: { label: "Luật Lao Động", short: "Bài 9", emoji: "👷" },
};

const QUIZ_DATA = [
  // ===================== BÀI 1: PHÁP LUẬT ĐẠI CƯƠNG =====================
  { id: 1, subject: "bai1", q: "Trong quy phạm: \"Người nào đối xử tàn ác, thường xuyên ức hiếp, ngược đãi hoặc làm nhục người lệ thuộc mình làm người đó tự sát, thì bị phạt tù từ hai năm đến bảy năm\", phần chế tài trong đây là thuộc chế tài nào?", a: "Chế tài hình sự" },
  { id: 2, subject: "bai1", q: "Điểm khác biệt cơ bản giữa quy phạm pháp luật và quy phạm đạo đức là gì?", a: "Quy phạm pháp luật mang tính bắt buộc và được đảm bảo thực hiện bởi nhà nước." },
  { id: 3, subject: "bai1", q: "Ở Việt Nam, văn bản luật do cơ quan nào dưới đây ban hành?", a: "Quốc hội" },
  { id: 4, subject: "bai1", q: "Quyền \"lập hiến và lập pháp\" thuộc về cơ quan nào dưới đây trong bộ máy nhà nước của Việt Nam?", a: "Quốc hội" },
  { id: 5, subject: "bai1", q: "Trong các cơ quan sau đây, cơ quan nào là cơ quan quản lý hành chính nhà nước?", a: "Chính phủ" },
  { id: 6, subject: "bai1", q: "Các thành tố của hệ thống pháp luật là:", a: "Quy phạm pháp luật, chế định pháp luật, ngành luật" },
  { id: 7, subject: "bai1", q: "Ngành luật nào điều chỉnh các quan hệ xã hội phát sinh trong lĩnh vực sở hữu, hợp đồng và thừa kế?", a: "Luật dân sự" },
  { id: 8, subject: "bai1", q: "Đặc điểm nào sau đây KHÔNG phải là đặc điểm của quy phạm pháp luật?", a: "Tính tùy ý áp dụng theo ý thích của cá nhân" },
  { id: 9, subject: "bai1", q: "Ủy ban nhân dân có thẩm quyền gì trong lĩnh vực quản lý đất đai?", a: "Quyết định giao đất, cho thuê đất theo quy định của pháp luật." },
  { id: 10, subject: "bai1", q: "Ai là người chịu trách nhiệm trực tiếp trước Hội đồng nhân dân về hoạt động của Ủy ban nhân dân?", a: "Chủ tịch UBND" },
  { id: 11, subject: "bai1", q: "Cơ quan nào dưới đây không thuộc hệ thống cơ quan xét xử trong bộ máy nhà nước của Việt Nam?", a: "Viện kiểm sát nhân dân" },
  { id: 12, subject: "bai1", q: "Căn cứ vào trình tự thành lập, cơ quan nhà nước được chia thành:", a: "Cơ quan do dân trực tiếp bầu ra và cơ quan không do dân trực tiếp bầu ra" },
  { id: 13, subject: "bai1", q: "Tổ chức và hoạt động của Bộ máy Nhà nước CHXHCN Việt Nam được thực hiện trên cơ sở những nguyên tắc nào?", a: "Phân chia quyền lực" },
  { id: 14, subject: "bai1", q: "Khi nghiên cứu về bộ máy Nhà nước Việt Nam thì khẳng định nào sau đây là đúng?", a: "Hội đồng nhân dân do nhân dân trực tiếp bầu ra" },
  { id: 15, subject: "bai1", q: "Ủy ban nhân dân được tổ chức ở những cấp hành chính nào?", a: "Cấp tỉnh và cấp xã" },
  { id: 16, subject: "bai1", q: "Theo quy định của pháp luật Việt Nam, khi các văn bản có quy định khác nhau về cùng một vấn đề thì áp dụng quy định của:", a: "Văn bản có hiệu lực pháp lý cao hơn" },
  { id: 17, subject: "bai1", q: "Trong Nhà nước CHXHCN Việt Nam, quyền lực Nhà nước thuộc về lực lượng nào dưới đây?", a: "Không đáp án nào đúng" },
  { id: 18, subject: "bai1", q: "Trong hệ thống văn bản quy phạm pháp luật của Việt Nam, văn bản quy phạm pháp luật có hiệu lực pháp lý cao nhất là:", a: "Hiến pháp" },
  { id: 19, subject: "bai1", q: "Chức năng nào dưới đây không phải là chức năng đối nội của Nhà nước CHXHCN Việt Nam?", a: "Mở rộng quan hệ hợp tác với các nước trên thế giới" },
  { id: 20, subject: "bai1", q: "Ở Việt Nam, hệ thống Tòa án quân sự bao gồm:", a: "Tòa án quân sự Trung ương; Tòa án quân sự Quân khu; Tòa án quân sự Khu vực và Quân chủng" },
  { id: 21, subject: "bai1", q: "Hệ thống pháp luật là gì?", a: "Tập hợp các quy phạm pháp luật có mối liên hệ nội tại, thống nhất và điều chỉnh các quan hệ xã hội." },
  { id: 22, subject: "bai1", q: "Nội dung trong văn bản quy phạm pháp luật phải đảm bảo:", a: "Phù hợp với Hiến pháp và không trái với văn bản pháp luật cấp cao hơn." },
  { id: 23, subject: "bai1", q: "Cấu thành của quy phạm pháp luật thông thường bao gồm:", a: "Giả định, quy định, chế tài" },
  { id: 24, subject: "bai1", q: "Khẳng định nào sau đây là đúng khi nói về Chủ tịch nước CHXHCN Việt Nam?", a: "Tất cả đáp án trên đều đúng" },
  { id: 25, subject: "bai1", q: "Chủ tịch nước là người thay mặt nước Cộng hoà xã hội chủ nghĩa Việt Nam về đối nội và đối ngoại", a: "Tất cả đáp án trên đều đúng" },
  { id: 26, subject: "bai1", q: "Ở Việt Nam, Chủ tịch nước có nhiệm kỳ bao nhiêu năm?", a: "5 năm" },
  { id: 27, subject: "bai1", q: "Người đứng đầu cơ quan hành pháp trong bộ máy nhà nước CHXH chủ nghĩa Việt Nam là:", a: "Thủ tướng chính phủ" },
  { id: 28, subject: "bai1", q: "Hệ thống văn bản quy phạm pháp luật của Việt Nam hiện nay bao gồm:", a: "Hiến pháp và văn bản pháp luật" },
  { id: 29, subject: "bai1", q: "Điều 23 khoản 1 đoạn 2 của Bộ luật Hình sự năm 2015, sửa đổi năm 2017 quy định: \"Hành vi gây thiệt hại trong tình thế cấp thiết không phải là tội phạm\". Trong quy phạm pháp luật này, phần quy định là:", a: "\"Không phải là tội phạm\"" },
  { id: 30, subject: "bai1", q: "Quốc hội là cơ quan nhà nước không có đặc điểm nào dưới đây?", a: "Cơ quan xét xử" },
  { id: 31, subject: "bai1", q: "Điều 19 của Hiến pháp năm 2013 quy định: \"Mọi người có quyền sống\". Quy phạm pháp luật này không có bộ phận nào?", a: "Phần chế tài" },
  { id: 32, subject: "bai1", q: "Văn bản quy phạm pháp luật là gì?", a: "Văn bản do cơ quan nhà nước có thẩm quyền ban hành, chứa đựng các quy phạm pháp luật." },
  { id: 33, subject: "bai1", q: "Chế tài hình sự được sử dụng khi có sự vi phạm:", a: "Chế tài hình sự được sử dụng khi có sự vi phạm Bộ luật hình sự" },
  { id: 34, subject: "bai1", q: "Trong bộ máy Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam thì Tòa án là cơ quan:", a: "Cả A, B, C đều đúng" },
  { id: 35, subject: "bai1", q: "Trong bộ máy Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam thì Viện Kiểm Sát là cơ quan:", a: "Cơ quan thực hành quyền công tố, kiểm sát hoạt động tư pháp" },
  { id: 36, subject: "bai1", q: "Một văn bản quy phạm pháp luật phải đáp ứng yêu cầu nào sau đây?", a: "Tất cả các ý trên" },
  { id: 37, subject: "bai1", q: "Ở Việt Nam, người thay mặt Nhà nước về đối nội và đối ngoại là:", a: "Chủ tịch nước" },
  { id: 38, subject: "bai1", q: "Trong quy phạm sau đây: \"Mọi người có quyền tự do kinh doanh trong những ngành nghề mà pháp luật không cấm\" (điều 33 Hiến pháp năm 2013), phần giả định là:", a: "\"Mọi người\"" },
  { id: 39, subject: "bai1", q: "Nhà nước CHXHCN Việt Nam, theo chức năng có những hệ thống cơ quan quyền lực nào?", a: "Cơ quan lập pháp, cơ quan hành pháp và cơ quan tư pháp" },
  { id: 40, subject: "bai1", q: "Tiêu chí nào dưới đây không được sử dụng để xác định cơ quan nhà nước thuộc bộ máy nhà nước?", a: "Cơ quan nhà nước hoạt động trên cơ sở kinh phí do tư nhân cung cấp" },
  { id: 41, subject: "bai1", q: "Chính phủ là cơ quan nhà nước có đặc điểm nào dưới đây?", a: "Chính phủ là cơ quan hành pháp" },
  { id: 42, subject: "bai1", q: "Tại sao cần có hệ thống văn bản quy phạm pháp luật?", a: "Tất cả các ý trên" },
  { id: 43, subject: "bai1", q: "Phần tử nhỏ nhất tạo nên hệ thống pháp luật Việt Nam là gì?", a: "Quy phạm pháp luật" },
  { id: 44, subject: "bai1", q: "Văn bản quy phạm pháp luật có giá trị cao nhất ở Việt Nam là:", a: "Hiến pháp" },
  { id: 45, subject: "bai1", q: "Nhà nước CHXHCN Việt Nam có hai chức năng cơ bản là:", a: "Đối nội và đối ngoại" },
  { id: 46, subject: "bai1", q: "Chọn phương án điền vào chỗ trống: \"…………. là văn bản quy phạm pháp luật do Quốc hội - Cơ quan quyền lực nhà nước cao nhất - ban hành\"", a: "Văn bản luật" },
  { id: 47, subject: "bai1", q: "Ngành luật nào không có trong hệ thống pháp luật Việt Nam?", a: "Ngành luật doanh nghiệp" },
  { id: 48, subject: "bai1", q: "Phần chế tài trong một quy phạm pháp luật nêu lên:", a: "Những biện pháp xử lý và áp dụng đối với chủ thể không thực hiện mệnh lệnh của Nhà nước nêu ở phần quy định" },
  { id: 49, subject: "bai1", q: "Hội đồng nhân dân được tổ chức ở các cấp nào?", a: "Cấp tỉnh, cấp huyện và cấp xã" },
  { id: 50, subject: "bai1", q: "Chức năng chính của Hội đồng nhân dân là gì?", a: "Thực hiện quyền giám sát và quyết định các vấn đề quan trọng của địa phương." },
  { id: 51, subject: "bai1", q: "Ủy ban nhân dân có chức năng ban hành luật để áp dụng trên toàn quốc. Đúng hay Sai", a: "Sai" },

  // ===================== BÀI 2: HIẾN PHÁP =====================
  { id: 52, subject: "bai2", q: "Quốc hội là cơ quan duy nhất có thẩm quyền sửa đổi Hiến pháp. Đúng hay Sai", a: "Đúng" },
  { id: 53, subject: "bai2", q: "Hiến pháp năm 2013 là Hiến pháp thứ 5 của Việt Nam. Đúng hay sai", a: "Đúng" },
  { id: 54, subject: "bai2", q: "Ở Việt Nam hiện nay, hệ thống tòa án được tổ chức gồm các cấp:", a: "Tất cả đều đúng" },
  { id: 55, subject: "bai2", q: "Hiến pháp Việt Nam hiện hành quy định rõ vai trò của Đảng Cộng sản Việt Nam là lực lượng lãnh đạo nhà nước và xã hội. Đúng hay sai?", a: "Đúng" },
  { id: 56, subject: "bai2", q: "Theo Hiến pháp năm 2013, thành phần kinh tế nhà nước:", a: "Giữ vai trò chủ đạo" },
  { id: 57, subject: "bai2", q: "Theo Hiến pháp năm 2013, nhận định nào dưới đây KHÔNG đúng khi nói về chế độ kinh tế?", a: "Kinh tế Việt Nam là kinh tế thị trường định hướng XHCH" },
  { id: 58, subject: "bai2", q: "Hiến pháp được ban hành bởi cơ quan nào?", a: "Quốc hội" },
  { id: 59, subject: "bai2", q: "Theo Hiến pháp năm 2013, nhiệm kỳ của Quốc hội và Hội đồng nhân dân các cấp là:", a: "5 năm" },
  { id: 60, subject: "bai2", q: "Hiến pháp bảo vệ quyền gì đối với trẻ em?", a: "Quyền được giáo dục và bảo vệ" },
  { id: 61, subject: "bai2", q: "Theo Hiến pháp năm 2013, công dân không có quyền nào dưới đây:", a: "Phải trung thành với Tổ quốc" },
  { id: 62, subject: "bai2", q: "Một trong những nội dung cốt lõi của Hiến pháp là gì?", a: "Quy định quyền lực tối cao thuộc về nhân dân." },
  { id: 63, subject: "bai2", q: "Nghĩa vụ của công dân đối với nhà nước trong Hiến pháp là gì?", a: "Tuân thủ pháp luật, đóng góp vào xây dựng và bảo vệ đất nước." },
  { id: 64, subject: "bai2", q: "Theo Hiến pháp năm 2013, chính sách giáo dục có mục đích là:", a: "Nâng cao dân trí, phát triển nguồn nhân lực, bồi dưỡng nhân tài" },
  { id: 65, subject: "bai2", q: "Hiến pháp khẳng định quyền bình đẳng trước pháp luật nhằm mục đích gì?", a: "Đảm bảo không ai bị phân biệt đối xử." },
  { id: 66, subject: "bai2", q: "Theo Hiến pháp Việt Nam năm 2013, thành phần kinh tế nào dưới đây giữ vai trò chủ đạo?", a: "Kinh tế nhà nước" },
  { id: 67, subject: "bai2", q: "Theo quy định tại Điều 9 của Hiến pháp năm 2013, cơ sở chính trị của chính quyền nhân dân là:", a: "Mặt trận tổ quốc" },
  { id: 68, subject: "bai2", q: "Theo Hiến pháp Việt Nam 2013, Chính phủ Việt Nam là gì?", a: "Cơ quan hành chính nhà nước cao nhất." },
  { id: 69, subject: "bai2", q: "Quyền con người thường được chia thành hai nhóm lớn là:", a: "Quyền dân sự và chính trị; quyền về kinh tế, xã hội và văn hóa" },
  { id: 70, subject: "bai2", q: "Để thực hiện chính sách Khoa học và Công nghệ theo Hiến pháp năm 2013, Nhà nước Việt Nam:", a: "Bảo hộ quyền sở hữu trí tuệ" },
  { id: 71, subject: "bai2", q: "Tính đến năm 2018, Việt Nam có mấy bản Hiến pháp?", a: "5" },
  { id: 72, subject: "bai2", q: "Tòa án Nhân dân có nhiệm vụ gì theo Hiến pháp Việt Nam 2013?", a: "Xét xử và đảm bảo công lý tại Việt Nam." },
  { id: 73, subject: "bai2", q: "Hiến pháp Việt Nam năm 2013 xác định phát triển khoa học và công nghệ là:", a: "Quốc sách hàng đầu, giữ vai trò then chốt trong sự nghiệp phát triển kinh tế - xã hội của đất nước." },
  { id: 74, subject: "bai2", q: "Theo Hiến pháp năm 2013, văn hóa Việt Nam được bảo tồn và phát triển với phương châm:", a: "Tiên tiến, đậm đà bản sắc dân tộc, tiếp thu tinh hoa văn hóa nhân loại" },
  { id: 75, subject: "bai2", q: "Nguyên tắc \"phân công và phối hợp giữa các cơ quan nhà nước\" được hiểu là gì?", a: "Mỗi cơ quan thực hiện chức năng riêng và phối hợp để đảm bảo quyền lực thống nhất." },
  { id: 76, subject: "bai2", q: "Ở Việt Nam, Hiến pháp do ai ban hành?", a: "Quốc hội" },
  { id: 77, subject: "bai2", q: "Nội dung của quyền kinh tế của công dân theo Hiến pháp năm 2013 là:", a: "Công dân có quyền tự do kinh doanh những ngành nghề mà pháp luật không cấm;" },
  { id: 78, subject: "bai2", q: "Theo Hiến pháp năm 2013, công dân nước Cộng hòa xã hội chủ nghĩa Việt Nam là:", a: "Người có quốc tịch Việt Nam" },
  { id: 79, subject: "bai2", q: "Chính phủ Việt Nam đặt ra mục tiêu 1 triệu doanh nghiệp hoạt động trên thị trường Việt Nam. Chính phủ đang thực hiện chính sách nào được quy định trong Hiến pháp năm 2013?", a: "Chính sách kinh tế" },
  { id: 80, subject: "bai2", q: "Ông Nguyễn Văn A là người Việt Nam sinh sống ở nước ngoài. Nhận định nào dưới đây là đúng?", a: "Ông Hải không còn là công dân Việt Nam nếu đã từ bỏ quốc tịch Việt Nam" },
  { id: 81, subject: "bai2", q: "Ông Hải không còn là công dân Việt Nam nếu đã nhập quốc tịch nước ngoài", a: "Đúng" },
  { id: 82, subject: "bai2", q: "Cô Phạm Hồng Vinh ký hợp đồng lao động với Doanh nghiệp X. Theo Hiến pháp năm 2013, cô Nguyễn Hồng Vinh đang thực hiện:", a: "Quyền lao động" },
  { id: 83, subject: "bai2", q: "Trách nhiệm bảo vệ Hiến pháp thuộc về ai?", a: "Tất cả các cơ quan nhà nước, tổ chức, cá nhân và công dân." },
  { id: 84, subject: "bai2", q: "Hằng năm, đến ngày 27-7, nhiều cơ quan, đoàn thể, tổ chức, cá nhân đi thăm các gia đình thương binh, liệt sỹ. Họ đang thực hiện chính sách nào được quy định trong Hiến pháp năm 2013?", a: "Chính sách xã hội" },
  { id: 85, subject: "bai2", q: "Công dân A (30 tuổi) đi bầu cử đại biểu quốc hội. Theo Hiến pháp năm 2013, Công dân A đang được hiện quyền gì?", a: "Quyền bầu cử vào cơ quan quyền lực nhà nước" },
  { id: 86, subject: "bai2", q: "Hiến pháp năm 2013 xác định mục đích phát triển kinh tế Việt Nam là:", a: "Tất cả đều đúng" },
  { id: 87, subject: "bai2", q: "Theo Hiến pháp năm 2013, bảo vệ Tổ quốc Việt Nam XHCN là:", a: "Tất cả đều đúng" },
  { id: 88, subject: "bai2", q: "Theo quy định tại Điều 4 Hiến pháp năm 2013, lực lượng lãnh đạo Nhà nước và xã hội ở Việt Nam là:", a: "Đảng cộng sản Việt Nam" },
  { id: 89, subject: "bai2", q: "Theo Hiến pháp năm 2013, cơ quan nào dưới đây không thuộc các cơ quan tư pháp của nước CHXHCN Việt Nam?", a: "Trọng tài thương mại" },
  { id: 90, subject: "bai2", q: "Hiến pháp năm 2013 quy định những nội dung cơ bản nào?", a: "Chế độ chính trị và chế độ kinh tế; chính sách xã hội, văn hóa, giáo dục, khoa học công nghệ, môi trường; quyền con người, quyền và nghĩa vụ cơ bản của công dân" },
  { id: 91, subject: "bai2", q: "Theo Hiến pháp năm 2013, hai chính sách được coi là quốc sách hàng đầu bao gồm:", a: "Giáo dục và Khoa học, công nghệ" },
  { id: 92, subject: "bai2", q: "Bản chất của Nhà nước CHXHCN Việt Nam là:", a: "Của dân, do dân và vì dân, tất cả quyền lực nhà nước đều thuộc về nhân dân" },
  { id: 93, subject: "bai2", q: "Theo Hiến pháp năm 2013, chính sách xã hội không nhằm mục đích nào dưới đây?", a: "Phát triển kinh tế để dân giàu, nước mạnh" },
  { id: 94, subject: "bai2", q: "Bản Hiến pháp hiện đang được áp dụng ở Việt Nam được ban hành năm:", a: "2013" },
  { id: 95, subject: "bai2", q: "Theo Hiến pháp năm 2013, mục đích của chính sách khoa học và công nghệ là:", a: "Tất cả đều đúng" },
  { id: 96, subject: "bai2", q: "Theo Hiến pháp năm 2013, người nước ngoài không có quốc tịch Việt Nam sinh sống tại Việt Nam:", a: "Hưởng đầy đủ các quy định của Hiến pháp về quyền con người" },
  { id: 97, subject: "bai2", q: "Cá nhân X được sinh ra trên lãnh thổ Việt Nam. Theo Hiến pháp năm 2013, cá nhân X là:", a: "Được hưởng đầy đủ các quy định của Hiến pháp về quyền con người." },

  // ===================== BÀI 3: LUẬT DÂN SỰ =====================
  { id: 98, subject: "bai3", q: "Một trong các nguyên tắc cơ bản của Luật Dân sự là:", a: "Tự do, tự nguyện cam kết, thỏa thuận." },
  { id: 99, subject: "bai3", q: "Hợp đồng dân sự có hiệu lực khi nào?", a: "Khi đáp ứng các điều kiện về năng lực pháp luật, tự nguyện và nội dung hợp pháp." },
  { id: 100, subject: "bai3", q: "Bà X bán cho ông Y một mảnh đất trị giá 5 tỷ đồng. Tuy nhiên, bà X và ông Y thỏa thuận chỉ ký hợp đồng trong đó giá trị mảnh đất ghi là 3 tỷ đồng. Trên thực tế, ông Y vẫn trả bà X đủ 5 tỷ đồng. Theo quy định của Bộ luật Dân sự năm 2015, hợp đồng ghi giá trị mảnh đất 3 tỷ đồng có thể bị tuyên bố vô hiệu vì:", a: "Giả tạo" },
  { id: 101, subject: "bai3", q: "Quyền chiếm hữu trong quyền sở hữu tài sản có nghĩa là gì?", a: "Nắm giữ và chi phối tài sản một cách hợp pháp." },
  { id: 102, subject: "bai3", q: "Theo quy định của Luật dân sự, quyền sở hữu tài sản bao gồm:", a: "Quyền chiếm hữu, quyền sử dụng và quyền định đoạt" },
  { id: 103, subject: "bai3", q: "Quan hệ nhân thân và quan hệ tài sản là đối tượng điều chỉnh của ngành luật nào sau đây?", a: "Luật Dân sự" },
  { id: 104, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, tiêu chí nào sau đây không được sử dụng để xác định một tổ chức là pháp nhân?", a: "Có thể sử dụng tài sản của các thành viên tổ chức để chịu trách nhiệm thay cho tổ chức" },
  { id: 105, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, trong trường hợp nào dưới đây, hợp đồng có thể bị tuyên bố vô hiệu?", a: "Cả ba đáp án trên đều đúng" },
  { id: 106, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, điều kiện nào sau đây không phải là điều kiện hiệu lực của hợp đồng?", a: "Mục đích của hợp đồng không được vi phạm điều cấm của pháp luật" },
  { id: 107, subject: "bai3", q: "Một hợp đồng dân sự sẽ chấm dứt trong trường hợp nào?", a: "Tất cả các trường hợp trên." },
  { id: 108, subject: "bai3", q: "Đâu không phải là nguyên tắc trong giao kết hợp đồng dân sự?", a: "Đảm bảo sự bình đẳng về mặt kinh tế giữa các chủ thể" },
  { id: 109, subject: "bai3", q: "Công ty A gửi cho Công ty B đề nghị bán 10 chiếc máy tính, giá mỗi chiếc là 12 triệu đồng, thời hạn giao hàng là 15 ngày sau ngày giao kết hợp đồng. Nhận được đề nghị này, Công ty B trả lời đồng ý mua 5 chiếc máy tính với giá và thời hạn như được ghi trong đề nghị. Nhận định nào sau đây là chính xác?", a: "Giữa hai bên chưa có hợp đồng" },
  { id: 110, subject: "bai3", q: "Hợp đồng dân sự là gì?", a: "Sự thỏa thuận giữa các bên về việc xác lập, thay đổi hoặc chấm dứt quyền, nghĩa vụ dân sự." },
  { id: 111, subject: "bai3", q: "Theo Bộ luật dân sự năm 2015, nguyên tắc nào dưới đây không phải là nguyên tắc của pháp luật dân sự Việt Nam?", a: "Nguyên tắc giao dịch có lợi" },
  { id: 112, subject: "bai3", q: "Nội dung chính của hợp đồng dân sự bao gồm?", a: "Đối tượng, quyền, nghĩa vụ, và phương thức giải quyết tranh chấp." },
  { id: 113, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, một bên không có quyền hủy bỏ hợp đồng trong trường hợp nào dưới đây?", a: "Bên kia vi phạm không nghiêm trọng nghĩa vụ hợp đồng" },
  { id: 114, subject: "bai3", q: "Ai có thể là chủ thể của hợp đồng dân sự?", a: "Cá nhân, pháp nhân và hộ gia đình." },
  { id: 115, subject: "bai3", q: "Anh A ăn trộm chiếc xe máy dựng ở vỉa hè. Theo Bộ luật Dân sự năm 2015, việc chiếm hữu của anh A đối với chiếc xe máy đó là:", a: "Chiếm hữu không có căn cứ pháp luật nhưng không ngay tình" },
  { id: 116, subject: "bai3", q: "Theo quy định của Luật dân sự, căn cứ nào sau đây không được coi là căn cứ xác lập quyền sở hữu tài sản hợp pháp?", a: "Do trộm cắp, chiếm đoạt bất hợp pháp không ngay tình của người khác" },
  { id: 117, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, quyền sử dụng đối với tài sản được hiểu là:", a: "Quyền khai thác công dụng, hưởng hoa lợi, lợi tức từ tài sản" },
  { id: 118, subject: "bai3", q: "Theo pháp luật dân sự Việt Nam, quan hệ nhân thân không gắn với tài sản không bao gồm?", a: "Quyền tác giả đối với tác phẩm văn học" },
  { id: 119, subject: "bai3", q: "Phương pháp nào dưới đây không phải là phương pháp điều chỉnh của pháp luật dân sự Việt Nam?", a: "Mệnh lệnh – quyền uy" },
  { id: 120, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, hợp đồng bắt buộc phải được lập bằng ngôn ngữ nào?", a: "Không có quy định" },
  { id: 121, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, chiếm hữu ngay tình là:", a: "Việc chiếm hữu mà người chiếm hữu có căn cứ để tin rằng mình có quyền đối với tài sản đang chiếm hữu" },
  { id: 122, subject: "bai3", q: "Em Nguyễn Văn An (5 tuổi) được mẹ cho tiền đi mua bánh ngọt để ăn. Em đã ra cửa hàng mua bánh ngọt mua 1 chiếc bánh ngọt giá 5 nghìn đồng. Nhận định nào dưới đây là đúng:", a: "Hợp đồng được giao kết giữa em An và cửa hàng bánh ngọt có thể bị tuyên bố vô hiệu" },
  { id: 123, subject: "bai3", q: "A là chủ sở hữu của vật nuôi, để vật nuôi đi lạc làm hư hỏng tài sản của B. Hỏi ai phải chịu trách nhiệm bồi thường trong trường hợp này?", a: "A – chủ sở hữu vật nuôi." },
  { id: 124, subject: "bai3", q: "Anh M đồng ý bán cho anh K một chiếc xe máy cũ. Hai bên thỏa thuận anh M sẽ giao xe cho anh K trong vòng 30 ngày kể từ ngày đồng ý bán. Tuy nhiên, 10 ngày sau, chiếc xe máy bị cháy. Theo quy định của Bộ luật Dân sự năm 2015, hợp đồng mua bán xe máy giữa anh M và anh K có thể bị tuyên bố vô hiệu vì:", a: "Đối tượng của hợp đồng không thể thực hiện được." },
  { id: 125, subject: "bai3", q: "Quan hệ nhân thân thuộc đối tượng điều chỉnh của Luật dân sự bao gồm:", a: "Quan hệ nhân thân gắn với tài sản và quan hệ nhân thân không gắn với tài sản" },
  { id: 126, subject: "bai3", q: "Quyền sở hữu tài sản được xác lập trong trường hợp nào?", a: "Tất cả các trường hợp trên." },
  { id: 127, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, chiếm hữu có căn cứ pháp luật KHÔNG bao gồm?", a: "Chủ sở hữu chiếm hữu tài sản" },
  { id: 128, subject: "bai3", q: "Tranh chấp về quyền sở hữu tài sản có thể được giải quyết bằng cơ quan nào dưới đây?", a: "Tòa án nhân dân" },
  { id: 129, subject: "bai3", q: "Khi tài sản bị người khác chiếm hữu bất hợp pháp, chủ sở hữu có quyền gì?", a: "Tất cả các quyền trên." },
  { id: 130, subject: "bai3", q: "Quyền sử dụng tài sản bị giới hạn trong trường hợp nào?", a: "Khi gây thiệt hại cho lợi ích quốc gia, dân tộc, lợi ích công cộng." },
  { id: 131, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, cá nhân có năng lực hành vi dân sự đầy đủ khi:", a: "Đủ 18 tuổi" },
  { id: 132, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, hợp đồng sẽ hình thành khi:", a: "Các bên đồng ý về tất cả các điều khoản của hợp đồng" },
  { id: 133, subject: "bai3", q: "Quyền định đoạt tài sản được thực hiện theo nguyên tắc nào?", a: "Phù hợp với quy định của pháp luật và đạo đức xã hội." },
  { id: 134, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, tổ chức nào dưới đây không phải là pháp nhân?", a: "Phòng phát triển chương trình của Trường Đại học FPT" },
  { id: 135, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, hợp đồng có thể bị tuyên bố vô hiệu do không tuân thủ quy định về hình thức nếu:", a: "Vi phạm quy định điều kiện có hiệu lực về hình thức" },
  { id: 136, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, điều kiện để thực hiện quyền định đoạt là:", a: "Cả ba đáp án trên" },
  { id: 137, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, hợp đồng dân sự bắt buộc phải được lập dưới hình thức nào:", a: "Không đáp án nào đúng" },
  { id: 138, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, một bên có quyền đơn phương chấm dứt thực hiện hợp đồng nếu:", a: "Cả ba đáp án trên đều đúng" },
  { id: 139, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, thời hiệu khởi kiện về hợp đồng là:", a: "3 năm kể từ ngày người có quyền yêu cầu biết hoặc phải biết quyền và lợi ích hợp pháp của mình bị xâm phạm" },
  { id: 140, subject: "bai3", q: "Người được chủ sở hữu ủy quyền quản lý tài sản có quyền gì?", a: "Quản lý và sử dụng tài sản trong phạm vi được ủy quyền." },
  { id: 141, subject: "bai3", q: "Theo Bộ luật Dân sự năm 2015, quyền nhân thân của cá nhân KHÔNG bao gồm?", a: "Quyền sở hữu tài sản hợp pháp" },
  { id: 142, subject: "bai3", q: "Người không phải là chủ sở hữu được định đoạt tài sản trong trường hợp nào?", a: "Khi được chủ sở hữu ủy quyền." },
  { id: 143, subject: "bai3", q: "Theo quy định của Bộ luật Dân sự năm 2015, các bên tham gia giao kết hợp đồng:", a: "Cả ba đáp án trên đều sai" },
  { id: 144, subject: "bai3", q: "Quan hệ nhân thân khác với quan hệ tài sản thuộc phạm vi điều chỉnh của pháp luật dân sự Việt Nam là:", a: "Quan hệ nhân thân không thể chuyển dịch được cho người khác" },
  { id: 145, subject: "bai3", q: "Công ty TNHH A (Việt Nam) ký hợp đồng xuất khẩu hàng thủ công mỹ nghệ với Công ty Cổ phần X (Singapore). Hợp đồng mà hai công ty ký kết không có đặc điểm nào dưới đây?", a: "Hợp đồng cung ứng dịch vụ" },
  { id: 146, subject: "bai3", q: "Theo pháp luật dân sự Việt Nam, chủ thể của quyền sở hữu là:", a: "Người đang sở hữu tài sản" },
  { id: 147, subject: "bai3", q: "Luật Dân sự điều chỉnh các quan hệ tài sản và quan hệ nhân thân dựa trên sự bình đẳng và độc lập giữa các chủ thể.", a: "Đúng" },
  { id: 148, subject: "bai3", q: "Mọi giao dịch dân sự bắt buộc phải được thực hiện bằng văn bản mới có giá trị pháp lý.", a: "Sai" },
  { id: 149, subject: "bai3", q: "Người chưa thành niên không có năng lực hành vi dân sự đầy đủ nhưng vẫn có thể tham gia giao dịch dân sự để đáp ứng nhu cầu thiết yếu.", a: "Đúng" },
  { id: 150, subject: "bai3", q: "Người đại diện theo pháp luật có quyền tự ý thực hiện mọi giao dịch dân sự thay cho người được đại diện.", a: "Sai" },
  { id: 151, subject: "bai3", q: "Người có năng lực hành vi dân sự nhưng tại thời điểm xác lập giao dịch không nhận thức và làm chủ được hành vi của mình thì giao dịch đó có thể bị tuyên vô hiệu.", a: "Đúng" },
  { id: 152, subject: "bai3", q: "Quyền nhân thân không thể chuyển giao cho người khác dưới bất kỳ hình thức nào.", a: "Đúng" },
  { id: 153, subject: "bai3", q: "Cá nhân không quốc tịch cư trú tại Việt Nam không có quyền tham gia giao dịch dân sự theo pháp luật Việt Nam.", a: "Sai" },
  { id: 154, subject: "bai3", q: "Chủ sở hữu tài sản có thể chuyển giao quyền chiếm hữu mà không cần chuyển giao quyền sử dụng hoặc định đoạt tài sản.", a: "Đúng." },

  // ===================== BÀI 4: LUẬT HÀNH CHÍNH =====================
  { id: 155, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính, các biện pháp xử phạt vi phạm hành chính chính bao gồm?", a: "Phạt tiền, cảnh cáo, Tước giấy phép, tịch thu tang vật, trục xuất" },
  { id: 156, subject: "bai4", q: "Phương pháp điều chỉnh đặc trưng của Luật Hành chính là gì?", a: "Mệnh lệnh, đơn phương." },
  { id: 157, subject: "bai4", q: "Quan hệ pháp luật hành chính nội bộ là:", a: "Quan hệ pháp luật điều chỉnh mối quan hệ giữa các chủ thể có mối quan hệ lệ thuộc về mặt tổ chức." },
  { id: 158, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính, biện pháp nào dưới đây là biện pháp ngăn chặn?", a: "Tạm giữ người có hành vi vi phạm pháp luật hành chính." },
  { id: 159, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính, mức phạt tiền đối với tổ chức vi phạm hành chính bằng bao nhiêu lần so với cá nhân?", a: "2 lần" },
  { id: 160, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính năm 2012, biện pháp ngăn chặn và bảo đảm xử lý vi phạm hành chính không bao gồm biện pháp nào dưới đây?", a: "Buộc thu hồi sản phẩm, hàng hóa không đảm bảo chất lượng" },
  { id: 161, subject: "bai4", q: "Hành vi vi phạm hành chính là gì?", a: "Hành vi xâm phạm trật tự, an toàn xã hội do cá nhân hoặc tổ chức thực hiện." },
  { id: 162, subject: "bai4", q: "Xử phạt vi phạm hành chính KHÔNG bao gồm nguyên tắc nào dưới đây?", a: "Một hành vi vi phạm hành chính có thể bị xử phạt nhiều lần" },
  { id: 163, subject: "bai4", q: "Cá nhân nào dưới đây KHÔNG phải chịu trách nhiệm do vi phạm hành chính?", a: "Cá nhân dưới 14 tuổi" },
  { id: 164, subject: "bai4", q: "Trong luật hành chính, mối quan hệ giữa Chính phủ và Bộ Tư pháp thuộc loại nào?", a: "Quan hệ pháp luật hành chính nội bộ." },
  { id: 165, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính năm 2012, biện pháp khắc phục hậu quả KHÔNG bao gồm biện pháp nào dưới đây?", a: "Tịch thu tang vật vi phạm pháp luật hành chính" },
  { id: 166, subject: "bai4", q: "Luật xử phạt vi phạm hành chính KHÔNG điều chỉnh quan hệ nào dưới đây?", a: "Quan hệ giữa hai cá nhân không liên quan đến pháp luật hành chính." },
  { id: 167, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính năm 2012, hình thức xử phạt nào dưới đây chỉ có thể là hình thức xử phạt chính?", a: "Cảnh cáo" },
  { id: 168, subject: "bai4", q: "Một hành vi vi phạm hành chính được áp dụng hình thức xử phạt nào nếu có tình tiết tăng nặng?", a: "Cảnh cáo" },
  { id: 169, subject: "bai4", q: "Một hành vi vi phạm hành chính có thể bị xử phạt bao nhiêu lần?", a: "1 lần." },
  { id: 170, subject: "bai4", q: "Cơ quan nào sau đây không thuộc cơ quan hành chính nhà nước?", a: "Hội đồng nhân dân" },
  { id: 171, subject: "bai4", q: "Nhận định nào sau đây đúng về vi phạm hành chính?", a: "Là hành vi vi phạm quy định pháp luật về quản lý nhà nước nhưng không phải tội phạm." },
  { id: 172, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính năm 2012, việc áp dụng biện pháp xử lý hành chính phải:", a: "Nhanh chóng, công khai, khách quan, đúng thẩm quyền, đảm bảo công bằng, đúng quy định" },
  { id: 173, subject: "bai4", q: "Ông K chạy xe mô tô vượt đèn đỏ. Ai sẽ chịu trách nhiệm nếu có trẻ em đi cùng?", a: "Chỉ ông K chịu trách nhiệm." },
  { id: 174, subject: "bai4", q: "Quyết định hành chính của cơ quan nhà nước mang tính chất nào?", a: "Quyền uy và bắt buộc thực hiện." },
  { id: 175, subject: "bai4", q: "Vi phạm hành chính phải đáp ứng yếu tố nào dưới đây để bị xử phạt?", a: "Tất cả các yếu tố trên." },
  { id: 176, subject: "bai4", q: "Vi phạm hành chính trong lĩnh vực giao thông thường bị xử lý như thế nào?", a: "Phạt tiền và tạm giữ phương tiện vi phạm." },
  { id: 177, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính năm 2012, người nào có nghĩa vụ chứng minh hành vi vi phạm hành chính?", a: "Người có thẩm quyền xử lý hành vi vi phạm hành chính" },
  { id: 178, subject: "bai4", q: "Cá nhân nào dưới đây phải chịu trách nhiệm do vi phạm hành chính gây ra bởi bất kỳ loại lỗi nào?", a: "Cá nhân từ đủ 16 tuổi trở lên" },
  { id: 179, subject: "bai4", q: "Quyền khiếu nại đối với quyết định xử phạt hành chính thuộc về ai?", a: "Người bị xử phạt hoặc người đại diện hợp pháp." },
  { id: 180, subject: "bai4", q: "Nhận định nào dưới đây là đúng khi nói về vi phạm hành chính?", a: "Hành vi có lỗi do cá nhân, tổ chức thực hiện" },
  { id: 181, subject: "bai4", q: "Nhận định nào dưới đây là đúng khi nói về lỗi trong vi phạm hành chính?", a: "Không có đáp án nào ở trên là đúng" },
  { id: 182, subject: "bai4", q: "Biện pháp khắc phục hậu quả trong xử phạt hành chính nhằm mục đích gì?", a: "Khôi phục lại trạng thái ban đầu trước khi xảy ra vi phạm." },
  { id: 183, subject: "bai4", q: "Theo Luật Xử lý vi phạm hành chính năm 2012, quản lý người nước ngoài vi phạm pháp luật Việt Nam trong thời gian làm thủ tục trục xuất là:", a: "Biện pháp ngăn chặn và bảo đảm xử lý vi phạm hành chính" },
  { id: 184, subject: "bai4", q: "Ông D lái xe tải vượt quá trọng tải cho phép và bị phát hiện. Hỏi: Hình thức xử phạt nào có thể áp dụng?", a: "Phạt tiền và tạm giữ phương tiện giao thông." },
  { id: 185, subject: "bai4", q: "Ông F bị phát hiện có hành vi buôn lậu tại cửa khẩu. Hỏi: Biện pháp ngăn chặn nào có thể được áp dụng?", a: "Tạm giữ ông F và tang vật vi phạm." },

  // ===================== BÀI 6: LUẬT HÌNH SỰ =====================
  { id: 186, subject: "bai6", q: "Theo Bộ luật Hình sự năm 2015, hình phạt tử hình chỉ được áp dụng cho tội phạm nào?", a: "Tội phạm đặc biệt nghiêm trọng" },
  { id: 187, subject: "bai6", q: "Người từ đủ 14 tuổi đến dưới 16 tuổi chịu trách nhiệm hình sự trong trường hợp nào?", a: "Tội phạm rất nghiêm trọng do cố ý hoặc tội đặc biệt nghiêm trọng." },
  { id: 188, subject: "bai6", q: "Theo Bộ luật Hình sự năm 2015, hình phạt \"trục xuất\" được áp dụng cho đối tượng nào?", a: "Người nước ngoài phạm tội trên lãnh thổ Việt Nam" },
  { id: 189, subject: "bai6", q: "Theo Bộ luật Hình sự, tội phạm đặc biệt nghiêm trọng có mức hình phạt cao nhất là gì?", a: "Chung thân hoặc tử hình." },
  { id: 190, subject: "bai6", q: "Hình phạt nào sau đây không phải là hình phạt bổ sung?", a: "Phạt cải tạo không giam giữ." },
  { id: 191, subject: "bai6", q: "Theo Luật Hình sự, pháp nhân thương mại phạm tội bị áp dụng hình phạt nào?", a: "Đình chỉ hoạt động có thời hạn." },
  { id: 192, subject: "bai6", q: "Theo Bộ luật Hình sự, tội phạm rất nghiêm trọng là gì?", a: "Tội phạm có mức hình phạt cao nhất từ trên 7 năm đến 15 năm tù." },
  { id: 193, subject: "bai6", q: "Theo pháp luật hình sự, loại tội phạm nào dưới đây có mức cao nhất của khung hình phạt là đến 3 năm tù?", a: "Tội phạm ít nghiêm trọng" },
  { id: 194, subject: "bai6", q: "Theo Bộ luật Hình sự năm 2015, thời hiệu truy cứu trách nhiệm hình sự là 10 năm được áp dụng đối với:", a: "Tội phạm nghiêm trọng" },
  { id: 195, subject: "bai6", q: "Pháp nhân thương mại phạm tội được định nghĩa thế nào trong Bộ luật Hình sự?", a: "Là tổ chức thực hiện hành vi nguy hiểm cho xã hội vì mục đích lợi nhuận." },
  { id: 196, subject: "bai6", q: "Theo pháp luật hình sự Việt Nam, hình phạt chính đối với pháp nhân thương mại phạm tội KHÔNG gồm:", a: "Phạt tù" },
  { id: 197, subject: "bai6", q: "Dấu hiệu nào sau đây không phải là dấu hiệu cơ bản của tội phạm?", a: "Tính vi phạm pháp luật" },
  { id: 198, subject: "bai6", q: "Theo Bộ luật Hình sự, hành vi buôn bán ma túy với số lượng lớn được xếp vào loại tội phạm nào?", a: "Tội phạm đặc biệt nghiêm trọng." },
  { id: 199, subject: "bai6", q: "Luật hình sự được điều chỉnh bằng phương pháp nào?", a: "Quyền uy" },
  { id: 200, subject: "bai6", q: "Người nào được coi là không có lỗi trong hành vi phạm tội?", a: "Cả 3 trường hợp trên." },
  { id: 201, subject: "bai6", q: "Trong mối quan hệ giữa Nhà nước và người phạm tội, người phạm tội có quyền:", a: "Yêu cầu Nhà nước chỉ được buộc mình chịu trách nhiệm hình sự đúng với quy định của pháp luật" },
  { id: 202, subject: "bai6", q: "Trong mối quan hệ giữa Nhà nước và người phạm tội, Nhà nước có quyền:", a: "Buộc người phạm tội phải thực hiện trách nhiệm hình sự" },
  { id: 203, subject: "bai6", q: "Tội phạm rất nghiêm trọng là tội phạm:", a: "Có khung hình phạt đến 15 năm tù" },
  { id: 204, subject: "bai6", q: "Theo pháp luật hình sự, nguyên tắc nào sau đây là đúng?", a: "Không ai bị coi là có tội khi chưa có bản án kết tội của Tòa án." },
  { id: 205, subject: "bai6", q: "Trong tình thế cấp thiêt, một người có hành vi gây thiệt hại cho lợi ích của cá nhân. Người này có bị coi là phạm tội không?", a: "Không, vì mọi hành vi trong tình thế cấp thiết đều được miễn trách nhiệm" },
  { id: 206, subject: "bai6", q: "Theo Bộ luật Hình sự năm 2015, hình phạt nào dưới đây KHÔNG phải là hình phạt chính:", a: "Cấm đảm nhiệm chức vụ" },
  { id: 207, subject: "bai6", q: "Ông B bị phát hiện sử dụng chất ma túy tại nhà riêng nhưng không gây hậu quả nghiêm trọng. Hỏi: Ông B có bị xử lý hình sự không?", a: "Có, vì hành vi này trái pháp luật hình sự." },
  { id: 208, subject: "bai6", q: "Ông C bị tấn công bất ngờ và do phòng vệ gây ra cái chết cho người tấn công để bảo vệ tính mạng mình. Hỏi: Hành vi của ông C có bị coi là phạm tội không?", a: "Không, nếu hành vi của ông C hoàn toàn cần thiết và phù hợp để bảo vệ tính mạng của mình theo quy định pháp luật." },
  { id: 209, subject: "bai6", q: "Nhận định nào sau đây đúng khi nói về pháp luật hình sự?", a: "Pháp luật hình sự quy định hình phạt có thể áp dụng cho các tội phạm" },
  { id: 210, subject: "bai6", q: "Công ty X không trang bị đầy đủ bảo hộ lao động cho công nhân, dẫn đến một vụ tai nạn lao động nghiêm trọng làm chết người. Hỏi: Công ty X và người đại diện theo pháp luật có bị truy cứu trách nhiệm hình sự không?", a: "Có, vì vi phạm quy định về an toàn lao động gây hậu quả nghiêm trọng, pháp nhân thương mại và người đại diện có thể bị xử lý hình sự." },
  { id: 211, subject: "bai6", q: "Hai nhóm quan hệ xã hội chính thuộc đối tượng điều chỉnh của pháp luật hình sự là?", a: "Các quan hệ xã hội giữa Nhà nước và người phạm tội; các quan hệ xã hội giữa Nhà nước và pháp nhân phải chịu trách nhiệm hình sự" },
  { id: 212, subject: "bai6", q: "Trong mối quan hệ giữa Nhà nước và người phạm tội, quyền nào sau đây là của người phạm tội?", a: "Yêu cầu được xét xử công bằng, đúng quy định pháp luật." },
  { id: 213, subject: "bai6", q: "Nhận định nào dưới đây là không đúng khi nói về hình phạt bổ sung, theo pháp luật hình sự Việt Nam?", a: "Là hình phạt có thể tuyên độc lập với hình phạt chính" },
  { id: 214, subject: "bai6", q: "Theo pháp luật hình sự Việt Nam, nhận định nào dưới đây là đúng khi nói về pháp nhân thương mại phạm tội?", a: "Không có đáp án nào đúng" },
  { id: 215, subject: "bai6", q: "Chủ thể nào dưới đây khi phạm tội phải chịu trách nhiệm hình sự?", a: "Công ty TNHH M" },
  { id: 216, subject: "bai6", q: "Bà B thực hiện hành vi trốn thuế trong thời gian dài và bị phát hiện. Bà B đã nộp lại số tiền thuế thiếu và tiền phạt chậm nộp trước khi bị khởi tố. Trường hợp này được xử lý như thế nào?", a: "Không bị truy cứu trách nhiệm hình sự." },
  { id: 217, subject: "bai6", q: "Theo pháp luật hình sự Việt Nam, một người bị coi là có tội khi:", a: "Bị tòa tuyên là có tội" },
  { id: 218, subject: "bai6", q: "Trong mối quan hệ giữa Nhà nước và người phạm tội, người phạm tội có nghĩa vụ:", a: "Chịu trách nhiệm hình sự" },
  { id: 219, subject: "bai6", q: "Bộ luật Hình sự năm 2015 được sửa đổi lần thứ nhất vào năm nào dưới đây?", a: "2017" },
  { id: 220, subject: "bai6", q: "Công ty X bị phát hiện buôn lậu hàng hóa cấm và thu lợi bất chính 2 tỷ đồng. Biện pháp tịch thu tài sản sẽ áp dụng trong trường hợp nào?", a: "Tài sản vi phạm pháp luật bị tịch thu toàn bộ." },
  { id: 221, subject: "bai6", q: "Một cá nhân bị kết án vì tội lạm dụng chức vụ, quyền hạn để chiếm đoạt tài sản. Ngoài hình phạt chính, hình phạt bổ sung nào phù hợp?", a: "Cả hai hình phạt trên." },
  { id: 222, subject: "bai6", q: "Nhận định nào dưới đây là đúng khi nói về loại tội phạm rất nghiêm trọng?", a: "Tội phạm rất nghiêm trọng có mức hình phạt cao nhất của khung hình phạt là từ 07 năm đến 15 năm tù." },
  { id: 223, subject: "bai6", q: "Theo pháp luật hình sự Việt Nam, người phạm tội là:", a: "Cá nhân" },
  { id: 224, subject: "bai6", q: "Công ty cổ phần M có hành vi buôn lậu và thu lời bất chính trên 500 triệu đồng. Nhận định nào sau đây đúng?", a: "Công ty cổ phần M đang thực hiện hành vi phạm tội" },
  { id: 225, subject: "bai6", q: "Tội phạm KHÔNG có dấu hiệu nào dưới đây?", a: "Không có đáp án nào đúng." },
  { id: 226, subject: "bai6", q: "Theo Bộ luật Hình sự 2015, hình phạt cải tạo không giam giữ được áp dụng cho loại tội phạm nào?", a: "Cải tạo không giam giữ" },
  { id: 227, subject: "bai6", q: "Hành vi chuẩn bị phạm tội luôn phải chịu trách nhiệm hình sự.", a: "Sai" },
  { id: 228, subject: "bai6", q: "Hình phạt cải tạo không giam giữ là một loại hình phạt chính trong hệ thống hình phạt của Bộ luật Hình sự Việt Nam.", a: "Đúng" },
  { id: 229, subject: "bai6", q: "Người phạm tội chưa đủ 18 tuổi được hưởng chính sách khoan hồng đặc biệt trong luật hình sự.", a: "Đúng" },
  { id: 230, subject: "bai6", q: "Hình phạt trục xuất có thể áp dụng đối với cả công dân Việt Nam và người nước ngoài.", a: "Sai" },
  { id: 231, subject: "bai6", q: "Bộ luật Hình sự Việt Nam không cho phép áp dụng các biện pháp giảm nhẹ hình phạt.", a: "Sai" },

  // ===================== BÀI 7: BẢO VỆ NGƯỜI TIÊU DÙNG =====================
  { id: 232, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, người tiêu dùng là:", a: "Người mua, sử dụng hàng hóa dịch vụ cho mục đích tiêu dùng, sinh hoạt của cá nhân, gia đình, cơ quan, tổ chức và không vì mục đích thương mại." },
  { id: 233, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, người nào dưới đây là người tiêu dùng?", a: "Công ty M mua nước uống cho nhân viên của mình" },
  { id: 234, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, nhận định nào sau đây đúng khi nói về khái niệm người tiêu dùng?", a: "Người tiêu dùng có thể là cá nhân và tổ chức" },
  { id: 235, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, người nào dưới đây KHÔNG phải là người tiêu dùng?", a: "Bà M mua sữa về để làm sữa chua bán" },
  { id: 236, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, một doanh nghiệp sản xuất hàng hóa cũng có thể là người tiêu dùng nếu:", a: "Doanh nghiệp đó mua giấy về để nhân viên sử dụng" },
  { id: 237, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng, người tiêu dùng KHÔNG có quyền nào dưới đây?", a: "Yêu cầu người bán cung cấp hàng hóa cho mình bất kỳ khi nào" },
  { id: 238, subject: "bai7", q: "Anh A sau khi đi ăn bát phở ở cửa hàng thì bị đau bụng. Kết quả kiểm tra xác định anh A bị ngộ độc từ bát phở đó. Anh A yêu cầu cửa hàng bán phở bồi thường cho mình 1 triệu đồng chi phí điều trị. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2019, việc anh A đòi 1 triệu đồng là anh A đang thực hiện quyền?", a: "Yêu cầu bồi thường thiệt hại" },
  { id: 239, subject: "bai7", q: "Ông M tham gia một hội thảo của Hiệp hội bảo vệ quyền lợi người tiêu dùng về thực tiễn áp dụng pháp luật bảo vệ quyền lợi người tiêu dùng. Tại hội thảo, ông M trình bày một số điểm để hoàn thiện pháp luật Việt Nam về bảo vệ quyền lợi người tiêu dùng. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2019, ông M đang thực hiện quyền:", a: "Tham gia xây dựng chính sách, pháp luật về bảo vệ quyền lợi người tiêu dùng" },
  { id: 240, subject: "bai7", q: "Bà K, sau khi sử dụng mỹ phẩm bị nổi mụn, đã nhờ Hội Bảo vệ quyền lợi người tiêu dùng tỉnh K đứng ra bảo vệ quyền lợi cho mình đối với hãng mỹ phẩm đã bán mỹ phẩm cho bà. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2019, bà K đang thực hiện quyền:", a: "Đề nghị tổ chức xã hội bảo vệ quyền lợi cho mình" },
  { id: 241, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng, quyền được cung cấp thông tin của người tiêu dùng bao gồm nội dung nào?", a: "Tất cả các đáp án trên" },
  { id: 242, subject: "bai7", q: "Doanh nghiệp vi phạm quyền lợi người tiêu dùng có thể bị xử phạt hành chính trong trường hợp nào sau đây?", a: "Tất cả các đáp án trên." },
  { id: 243, subject: "bai7", q: "Bà H sau khi uống xong chai nước đã để chai nhựa đựng nước vào thùng rác tái chế. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, bà H đang thực hiện nghĩa vụ:", a: "Tuân thủ quy định về bảo vệ môi trường" },
  { id: 244, subject: "bai7", q: "Ông P, sau khi phát hiện một cửa hàng bán giò lụa có sử dụng hàn the khi chế biến giò, đã báo cho cơ quan quản lý thị trường đến kiểm tra cửa hàng. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, ông P đang thực hiện nghĩa vụ:", a: "Thông tin kịp thời, chính xác cho cơ quan nhà nước khi phát hiện hàng hóa không đảm bảo an toàn cho người tiêu dùng" },
  { id: 245, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, tổ chức kinh doanh hàng hóa dịch vụ KHÔNG bao gồm:", a: "Hội sinh viên trường N bán hàng gây quỹ từ thiện" },
  { id: 246, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, nhận định nào dưới đây là đúng khi nói về các cá nhân hoạt động thương mại độc lập, thường xuyên và KHÔNG phải đăng ký kinh doanh?", a: "Họ không phải là thương nhân" },
  { id: 247, subject: "bai7", q: "Luật Bảo vệ quyền lợi người tiêu dùng không áp dụng đối với trường hợp nào sau đây?", a: "Hàng hóa sử dụng cho mục đích sản xuất." },
  { id: 248, subject: "bai7", q: "Quyền nào sau đây của người tiêu dùng được pháp luật bảo vệ?", a: "Quyền được an toàn về sức khỏe và tài sản khi sử dụng sản phẩm." },
  { id: 249, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, người nào sau đây KHÔNG được coi là tổ chức kinh doanh hàng hóa, dịch vụ?", a: "Tổ chức phi chính phủ" },
  { id: 250, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, tổ chức, cá nhân kinh doanh hàng hóa, dịch vụ phải là người cung cấp hàng hóa, dịch vụ nhằm mục đích:", a: "Sinh lợi" },
  { id: 251, subject: "bai7", q: "Tổ chức bảo vệ quyền lợi người tiêu dùng có trách nhiệm gì?", a: "Đại diện người tiêu dùng khiếu nại hoặc khởi kiện." },
  { id: 252, subject: "bai7", q: "Theo pháp luật Việt Nam hiện hành, tổ chức, người nào dưới đây là cá nhân hoạt động thương mại độc lập, thường xuyên KHÔNG phải đăng ký kinh doanh?", a: "Người buôn bán vặt" },
  { id: 253, subject: "bai7", q: "Trong trường hợp nào dưới đây, người tiêu dùng không được trả lại hàng?", a: "Sản phẩm đã qua sử dụng nhưng không có lỗi." },
  { id: 254, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, tổ chức, cá nhân kinh doanh hàng hóa, dịch vụ KHÔNG có trách nhiệm nào dưới đây?", a: "Thu tiền bán hàng từ người tiêu dùng" },
  { id: 255, subject: "bai7", q: "Công ty K, sau khi phát hiện một lô hàng hóa đã bán ra thị trường bị nhiễm độc, đã thu lại lô hàng đó. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, công ty K đang thực hiện trách nhiệm:", a: "Thu hồi hàng hóa có khuyết tật" },
  { id: 256, subject: "bai7", q: "Người tiêu dùng có thể yêu cầu doanh nghiệp làm gì khi sản phẩm bị lỗi?", a: "Tất cả các đáp án trên." },
  { id: 257, subject: "bai7", q: "Chị N mua một gói dịch vụ làm đẹp nhưng không nhận được đúng như cam kết. Theo quy định, chị N có thể làm gì?", a: "Tất cả các phương án trên." },
  { id: 258, subject: "bai7", q: "Công ty P sau khi bán một hợp đồng bảo hiểm nhân thọ cho bà M đã cung cấp cho bà M một hóa đơn. Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, công ty P đang thực hiện trách nhiệm:", a: "Cung cấp thông tin về dịch vụ cho người tiêu dùng" },
  { id: 259, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, tổ chức nào dưới đây là tổ chức xã hội tham gia bảo vệ quyền lợi người tiêu dùng?", a: "Hiệp hội bảo vệ quyền lợi người tiêu dùng" },
  { id: 260, subject: "bai7", q: "Hành vi nào sau đây không phải là vi phạm quyền lợi người tiêu dùng?", a: "Từ chối đổi trả khi sản phẩm không có lỗi." },
  { id: 261, subject: "bai7", q: "Nghĩa vụ nào sau đây không thuộc về người tiêu dùng?", a: "Chịu trách nhiệm về lỗi kỹ thuật của sản phẩm." },
  { id: 262, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, trách nhiệm nào dưới đây là trách nhiệm của tổ chức xã hội bảo vệ quyền lợi người tiêu dùng?", a: "Độc lập khảo sát về chất lượng của hàng hóa" },
  { id: 263, subject: "bai7", q: "Tổ chức nào có trách nhiệm hỗ trợ người tiêu dùng khi phát hiện vi phạm?", a: "Tất cả các đáp án trên." },
  { id: 264, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, trừ khi có thỏa thuận khác, kết quả thương lượng thành giữa tổ chức, cá nhân kinh doanh hàng hóa, dịch vụ với người tiêu dùng phải được lập bằng:", a: "Văn bản" },
  { id: 265, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, khi tổ chức, cá nhân kinh doanh hàng hóa dịch vụ và người tiêu dùng lựa chọn hòa giải làm phương thức giải quyết tranh chấp, việc hòa giải có thể được tiến hành bởi người thứ ba là:", a: "Tổ chức hòa giải" },
  { id: 266, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, nguyên tắc thực hiện hòa giải KHÔNG bao gồm:", a: "Đảm bảo tối đa lợi ích của người tiêu dùng" },
  { id: 267, subject: "bai7", q: "Khi người tiêu dùng phát hiện sản phẩm có nguy cơ gây hại, họ nên làm gì?", a: "Tất cả các phương án trên." },
  { id: 268, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, văn bản về kết quả hòa giải thành KHÔNG cần có nội dung nào sau đây?", a: "Cam kết của các bên về việc sẽ không khởi kiện ra tòa án" },
  { id: 269, subject: "bai7", q: "Thời gian bảo hành tối thiểu mà doanh nghiệp phải cung cấp cho sản phẩm tiêu dùng thông thường là bao lâu?", a: "Theo thỏa thuận giữa hai bên." },
  { id: 270, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, trong giải quyết tranh chấp về bảo vệ quyền lợi người tiêu dùng, người có nghĩa vụ chứng minh lỗi gây ra thiệt hại là:", a: "Tổ chức, cá nhân kinh doanh hàng hóa dịch vụ" },
  { id: 271, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, nếu người tiêu dùng yêu cầu tổ chức kinh doanh hàng hóa phải bồi thường, nghĩa vụ chứng minh thiệt hại thuộc về:", a: "Người tiêu dùng" },
  { id: 272, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, khi người tiêu dùng khởi kiện vụ án dân sự để bảo vệ quyền, lợi ích hợp pháp của mình, thì:", a: "Không phải nộp tạm ứng án phí" },
  { id: 273, subject: "bai7", q: "Doanh nghiệp không có nghĩa vụ phải thu hồi sản phẩm nếu phát hiện chúng gây nguy hiểm cho người tiêu dùng.", a: "Sai" },
  { id: 274, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, bản án của tòa án giải quyết vụ án dân sự về bảo vệ quyền lợi người tiêu dùng do tổ chức xã hội khởi kiện phải được:", a: "Niêm yết công khai tại trụ sở của tổ chức xã hội khởi kiện" },
  { id: 275, subject: "bai7", q: "Doanh nghiệp không phải chịu trách nhiệm đối với trường hợp nào dưới đây?", a: "Hàng hóa giao không đúng như mô tả ban đầu." },
  { id: 276, subject: "bai7", q: "Doanh nghiệp chỉ phải cung cấp thông tin về giá cả, không cần công bố nguồn gốc hàng hóa.", a: "Sai" },
  { id: 277, subject: "bai7", q: "Doanh nghiệp có thể từ chối trách nhiệm bảo hành nếu người tiêu dùng làm hỏng sản phẩm do sử dụng không đúng hướng dẫn.", a: "Đúng" },
  { id: 278, subject: "bai7", q: "Khi doanh nghiệp gây thiệt hại cho người tiêu dùng, họ có thể bị xử phạt hành chính hoặc truy cứu trách nhiệm hình sự.", a: "Đúng" },
  { id: 279, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, người tiêu dùng sẽ không phải nộp tạm ứng án phí khi khởi kiện ra tòa để:", a: "Bảo vệ cho quyền và lợi ích hợp pháp của chính mình" },
  { id: 280, subject: "bai7", q: "Theo Luật Bảo vệ quyền lợi người tiêu dùng năm 2023, ai là người có thẩm quyền quyết định bên có lỗi trong vụ án dân sự về bảo vệ quyền lợi người tiêu dùng?", a: "Tòa án." },

  // ===================== BÀI 8: PHÒNG CHỐNG THAM NHŨNG =====================
  { id: 281, subject: "bai8", q: "Ông H là cán bộ quản lý tại một cơ quan nhà nước. Trong quá trình phê duyệt hồ sơ xây dựng, ông H đã yêu cầu doanh nghiệp chi trả 50 triệu đồng để hoàn tất thủ tục nhanh hơn. Hành vi của ông H thuộc loại nào theo Luật Phòng, chống tham nhũng?", a: "Nhũng nhiễu vì vụ lợi." },
  { id: 282, subject: "bai8", q: "Ông K là giám đốc sở giáo dục và đào tạo đã sử dụng 2 tỷ đồng từ ngân sách nhà nước để chi tiêu cá nhân. Hành vi này được xác định là:", a: "Tham ô tài sản." },
  { id: 283, subject: "bai8", q: "Chủ thể của tham nhũng là:", a: "Người có chức vụ, quyền hạn" },
  { id: 284, subject: "bai8", q: "Hành vi nào sau đây không phải là hành vi tham nhũng", a: "Ký duyệt hồ sơ đúng quy trình, tiêu chuẩn." },
  { id: 285, subject: "bai8", q: "Tác hại về chính trị của tham nhũng bao gồm:", a: "Làm giảm sút lòng tin của dân chúng vào sự lãnh đạo của Đảng" },
  { id: 286, subject: "bai8", q: "Ông M làm giám đốc Sở Tài chính tỉnh K. Trong quá trình tại nhiệm, ông ấy đã chiếm đoạt 1 tỷ ngân sách nhà nước phục vụ cho hoạt động của Sở Tài chính. Hành vi của ông M, theo Luật Phòng, chống tham nhũng năm 2018, là:", a: "Tham ô tài sản" },
  { id: 287, subject: "bai8", q: "Tham nhũng không có tác hại nào sau đây?", a: "Tăng cường khả năng cạnh tranh của nền kinh tế." },
  { id: 288, subject: "bai8", q: "Trách nhiệm nào dưới đây là của công dân trong công tác phòng, chống tham nhũng:", a: "Trách nhiệm tham gia phòng, chống tham nhũng" },
  { id: 289, subject: "bai8", q: "Nguyên nhân tham nhũng nào sau đây không thuộc nhóm nguyên nhân khách quan:", a: "Quá trình chuyển đổi cơ chế, tồn tại và đan xen giữa cái mới và cái cũ" },
  { id: 290, subject: "bai8", q: "Vì người có hành vi tham nhũng là người có chức vụ, quyền hạn, trình độ và thực hiện hành vi tham nhũng tinh vi, nên:", a: "Việc thu thập chứng cứ để chứng minh hành vi tham nhũng là cực kỳ khó khăn" },
  { id: 291, subject: "bai8", q: "Theo Luật Phòng, chống tham nhũng năm 2018, hành vi nào dưới đây là hành vi tham nhũng trong khu vực nhà nước:", a: "Lợi dụng chức vụ, quyền hạn gây ảnh hưởng đối với người khác để trục lợi" },
  { id: 292, subject: "bai8", q: "Khi tố cáo hành vi tham nhũng, công dân không có trách nhiệm nào dưới đây?", a: "Số tiền mà người có hành vi tham nhũng có được" },
  { id: 293, subject: "bai8", q: "Tham nhũng không có đặc điểm nào dưới đây?", a: "Chủ thể tham nhũng là người giàu có" },
  { id: 294, subject: "bai8", q: "Trong quá trình tham dự đấu thầu tại dự án N của tỉnh H do Sở Giao thông vận tải làm chủ đầu tư, để có thể thắng thầu, giám đốc công ty M (thuộc lĩnh vực tư nhân) đã đưa cho giám đốc Sở giao thông vận tải 200 triệu đồng. Công ty M sau đó trúng thầu. Hành vi của giám đốc công ty M, theo Luật Phòng, chống tham nhũng năm 2018, là:", a: "Đưa hối hộ để giải quyết công việc của doanh nghiệp" },
  { id: 295, subject: "bai8", q: "Theo Luật Phòng, chống tham nhũng năm 2018, hành vi tham nhũng là hành vi:", a: "Bị cấm" },
  { id: 296, subject: "bai8", q: "Lợi ích mà người tham nhũng đạt được bao gồm:", a: "Lợi ích vật chất và lợi ích phi vật chất" },
  { id: 297, subject: "bai8", q: "Một trong những nguyên nhân của tham nhũng là nạn quà cáp, hối lộ. Đây là nguyên nhân xuất phát từ:", a: "Tập quán văn hóa" },
  { id: 298, subject: "bai8", q: "Công tác phòng, chống tham nhũng không có ý nghĩa nào dưới đây?", a: "Đảm bảo sự phát triển đầy đủ của tất cả các thành phần kinh tế" },
  { id: 299, subject: "bai8", q: "Người nào dưới đây không thể là chủ thể tham nhũng?", a: "Người lao động trong doanh nghiệp" },
  { id: 300, subject: "bai8", q: "Trách nhiệm của cá nhân tham gia phòng, chống tham nhũng không bao gồm:", a: "Xây dựng quy chế về phòng, chống tham nhũng tại thôn, xóm, tổ dân phố" },
  { id: 301, subject: "bai8", q: "Người nào dưới đây có thể là chủ thể tham nhũng?", a: "Ông A là giám đốc của một công ty TNHH một thành viên mà Nhà nước là chủ sở hữu" },
  { id: 302, subject: "bai8", q: "Trong công tác phòng, chống tham nhũng, Ban thanh tra nhân dân không có trách nhiệm nào dưới đây:", a: "Trực tiếp xem xét đơn kiến nghị và xác minh hành vi tham nhũng" },
  { id: 303, subject: "bai8", q: "Tham nhũng là hành vi của người có chức vụ, quyền hạn nhằm mục đích gì?", a: "Vụ lợi" },
  { id: 304, subject: "bai8", q: "Tham nhũng là hành vi của:", a: "Người có chức vụ, quyền hạn" },
  { id: 305, subject: "bai8", q: "Tác hại về xã hội của tham nhũng không bao gồm:", a: "Làm suy yếu khả năng cạnh tranh của nền kinh tế" },
  { id: 306, subject: "bai8", q: "Theo Luật Phòng, chống tham nhũng năm 2018, hành vi nào dưới đây không bị cấm?", a: "Tố cáo hành vi tham nhũng" },
  { id: 307, subject: "bai8", q: "Hành vi nào sau đây không thuộc nhóm hành vi tham nhũng theo quy định của pháp luật hiện hành:", a: "Giảm bớt hao phí trong sử dụng tiền, tài sản, lao động, thời gian lao động và tài nguyên thiên nhiên nhưng vẫn đạt được mục tiêu đã định" },
  { id: 308, subject: "bai8", q: "Ông N làm giám đốc Sở giáo dục và đào tạo tỉnh Y. Ông N đã nhận từ gia đình thí sinh M 500 triệu đồng để sửa điểm thi tốt nghiệp cho thí sinh M. Hành vi của ông N, theo Luật Phòng, chống tham nhũng năm 2018, là:", a: "Nhận hối lộ" },
  { id: 309, subject: "bai8", q: "Cơ quan, tổ chức và đơn vị khu vực nhà nước thuộc phạm vi điều chỉnh của Luật Phòng, chống tham nhũng năm 2018, không bao gồm:", a: "Phòng Thương mại và Công nghiệp Việt Nam" },
  { id: 310, subject: "bai8", q: "Phạm vi điều chỉnh của Luật Phòng, chống tham nhũng năm 2018, không bao gồm:", a: "Phòng Thương mại và Công nghiệp Việt Nam" },
  { id: 311, subject: "bai8", q: "Ông Y là giám đốc công ty TNHH PQL. Trong thời gian làm việc tại đây, ông Y đã buộc Kế toán trưởng phải xuất 2 tỷ đồng tiền mặt của công ty để phục vụ cho các mục đích tiêu dùng cá nhân của mình. Hành vi của ông Y, theo quy định của Luật Phòng, chống tham nhũng năm 2018, là:", a: "Tham ô tài sản" },
  { id: 312, subject: "bai8", q: "Nguyên nhân tham nhũng nào sau đây không thuộc nhóm nguyên nhân chủ quan:", a: "Chính sách pháp luật chưa đầy đủ, thiếu đồng bộ, thiếu nhất quán" },
  { id: 313, subject: "bai8", q: "Theo Luật Phòng, chống tham nhũng năm 2018, hành vi nào dưới đây bị cấm?", a: "Đe dọa người tố cáo hành vi tham nhũng" },
  { id: 314, subject: "bai8", q: "Hành vi nào dưới đây không thuộc hành vi giả mạo trong công tác?", a: "Không có đáp án nào đúng" },
  { id: 315, subject: "bai8", q: "Theo Luật Phòng, chống tham nhũng năm 2018, hành vi tham nhũng ngoài khu vực nhà nước không bao gồm:", a: "Tham ô tài sản" },
  { id: 316, subject: "bai8", q: "Nguyên nhân nào dưới đây không phải là nguyên nhân của tham nhũng ở Việt Nam?", a: "Môi trường kinh doanh đang ngày càng được cải thiện" },
  { id: 317, subject: "bai8", q: "Ông K làm trưởng phòng Quản lý đô thị của Quận P. Ông K đã nhận một khoản tiền từ bà P để \"lờ\" đi sai phạm trong xây dựng của bà P. Hành vi của ông K, theo Luật Phòng, chống tham nhũng năm 2018, là:", a: "Không thực hiện nhiệm vụ, công vụ vì vụ lợi" },
  { id: 318, subject: "bai8", q: "Theo Luật Phòng, chống tham nhũng năm 2018, hành vi tham nhũng được chia thành hai nhóm là:", a: "Hành vi tham nhũng trong khu vực nhà nước và hành vi tham nhũng trong khu vực ngoài nhà nước" },
  { id: 319, subject: "bai8", q: "Bà Q là cán bộ hộ tịch của phường N. Trong quá trình giải quyết thủ tục hành chính cho anh L, bà Q buộc anh L phải nộp thêm một loại giấy tờ mà pháp luật không quy định. Sau đó anh L đưa cho bà Q 2 triệu đồng và bà Q đã giải quyết thủ tục hành chính cho anh L mà không cần loại giấy tờ đó. Hành vi của bà Q, theo Luật Phòng, chống tham nhũng năm 2018, là:", a: "Nhũng nhiễu vì vụ lợi" },
  { id: 320, subject: "bai8", q: "Ông Q làm giám đốc Sở giáo dục và đào tạo tỉnh X. Trong thời gian tại vị, ông Q đã yêu cầu cấp dưới chỉnh sửa thông tin trên bằng tốt nghiệp phổ thông của mình từ loại Khá thành loại Giỏi. Hành vi của ông K, theo Luật Phòng, chống tham nhũng năm 2018, là:", a: "Giả mạo trong công tác." },

  // ===================== BÀI 9: LUẬT LAO ĐỘNG =====================
  { id: 321, subject: "bai9", q: "Nhận định nào dưới đây là đúng khi nói về quyền của người sử dụng lao động theo Bộ luật Lao động năm 2019?", a: "Người sử dụng lao động có quyền đóng cửa tạm thời nơi làm việc" },
  { id: 322, subject: "bai9", q: "Theo Bộ luật Lao động năm 2019, khi sử dụng người chưa đủ 15 tuổi làm việc, người sử dụng lao động KHÔNG phải:", a: "Tổ chức lớp học văn hóa cho người lao động chưa đủ 15 tuổi" },
  { id: 323, subject: "bai9", q: "Công ty TNHH A tuyển bà Q làm nhân viên tạp vụ với thời hạn 36 tháng. Theo quy định của Bộ luật Dân sự năm 2019, hợp đồng lao động với bà Q phải được lập dưới hình thức nào?", a: "Văn bản" },
  { id: 324, subject: "bai9", q: "Cửa hàng M tuyển sinh viên A làm nhân viên bán hàng bán thời gian trong thời gian 24 tháng. Hợp đồng lao động giữa cửa hàng M và sinh viên A, theo quy định của Bộ luật Lao động năm 2019, phải được lập thành mấy bản?", a: "2 bản" },
  { id: 325, subject: "bai9", q: "Công ty P ký hợp đồng lao động 12 tháng với ông Q. Hết thời hạn 12 tháng, ông Q vẫn tiếp tục làm việc nhưng công ty P không ký hợp đồng lao động mới. Theo Bộ luật Lao động năm 2019, nhận định nào dưới đây đúng?", a: "Hợp đồng lao động 12 tháng trở thành hợp đồng lao động không xác định thời hạn" },
  { id: 326, subject: "bai9", q: "Quy định nào dưới đây là bắt buộc trong nội quy lao động?", a: "An toàn lao động và vệ sinh lao động." },
  { id: 327, subject: "bai9", q: "Hợp đồng lao động không xác định thời hạn có thể kết thúc khi nào?", a: "Khi một bên đơn phương chấm dứt hợp đồng đúng quy định." },
  { id: 328, subject: "bai9", q: "Theo Bộ luật Lao động năm 2019, khi một bên muốn sửa đổi, bổ sung hợp đồng lao động, bên đó phải thông báo cho bên kia trước ít nhất", a: "3 ngày làm việc" },
  { id: 329, subject: "bai9", q: "Theo Bộ luật Lao động năm 2019, khi một bên có yêu cầu sửa đổi, bổ sung hợp đồng lao động mà các bên không đạt được thỏa thuận về việc này, thì nhận định nào sau đây là đúng?", a: "Hợp đồng lao động vẫn tiếp tục được thực hiện" },
  { id: 330, subject: "bai9", q: "Theo Bộ luật Lao động năm 2019, việc trả lương được thực hiện theo nguyên tắc nào dưới đây?", a: "Trực tiếp, đầy đủ, đúng hạn" },
  { id: 331, subject: "bai9", q: "Khi tranh chấp lao động xảy ra, phương thức giải quyết ưu tiên đầu tiên là gì?", a: "Hòa giải." },
  { id: 332, subject: "bai9", q: "Thời giờ làm việc tối đa của người lao động trong một tuần theo Bộ luật Lao động 2019 là bao nhiêu?", a: "48 giờ." },
  { id: 333, subject: "bai9", q: "Nguyên tắc nào dưới đây KHÔNG thuộc nguyên tắc cơ bản của Luật Lao động?", a: "Tạo ưu thế cho người sử dụng lao động trong mọi trường hợp." },
  { id: 334, subject: "bai9", q: "Đối tượng nào dưới đây thuộc phạm vi điều chỉnh của Luật Lao động?", a: "Người lao động làm việc theo hợp đồng lao động." },
  { id: 335, subject: "bai9", q: "Theo Bộ luật Lao động năm 2019, nội quy lao động bằng văn bản bắt buộc phải có đối với người sử dụng lao động từ:", a: "Từ 10 lao động trở lên" },
  { id: 336, subject: "bai9", q: "Luật Lao động khuyến khích điều gì trong mối quan hệ giữa người lao động và người sử dụng lao động?", a: "Các thỏa thuận có lợi hơn cho người lao động." },
  { id: 337, subject: "bai9", q: "Các nội dung bắt buộc trong hợp đồng lao động bao gồm?", a: "Công việc phải làm, tiền lương, thời gian làm việc và nghỉ ngơi." },
  { id: 338, subject: "bai9", q: "Người sử dụng lao động cần làm gì trước khi xử lý kỷ luật lao động?", a: "Tất cả các bước trên." },
  { id: 339, subject: "bai9", q: "Hình thức xử lý kỷ luật lao động cao nhất là gì?", a: "Sa thải." },
  { id: 340, subject: "bai9", q: "Người sử dụng lao động có trách nhiệm gì khi người lao động làm việc thêm giờ?", a: "Tất cả các trách nhiệm trên." },
  { id: 341, subject: "bai9", q: "Thỏa ước lao động tập thể không được phép có nội dung gì?", a: "Vi phạm pháp luật hoặc trái đạo đức xã hội." },
  { id: 342, subject: "bai9", q: "Quyết định sa thải người lao động có hiệu lực khi nào?", a: "Sau khi họp xử lý kỷ luật lao động và thông báo cho người lao động." },
  { id: 343, subject: "bai9", q: "Các hình thức xử lý kỷ luật lao động bao gồm những gì?", a: "Khiển trách, cảnh cáo, kéo dài thời hạn nâng lương, sa thải." },
  { id: 344, subject: "bai9", q: "Người sử dụng lao động phải có nghĩa vụ gì khi tổ chức làm thêm giờ?", a: "Bảo đảm không vượt quá 12 giờ trong một ngày, 30 giờ trong một tháng." },
  { id: 345, subject: "bai9", q: "Người lao động được nghỉ làm việc hưởng nguyên lương trong các trường hợp nào sau đây?", a: "Nghỉ Tết Dương lịch, Tết Âm lịch, Ngày Quốc tế Lao động, Ngày Quốc khánh." },
  { id: 346, subject: "bai9", q: "Ai có quyền gia nhập tổ chức đại diện người lao động tại cơ sở, bao gồm Công đoàn Việt Nam?", a: "Mọi người lao động làm việc theo hợp đồng lao động." },
  { id: 347, subject: "bai9", q: "Anh A làm việc tại công ty X theo hợp đồng lao động xác định thời hạn 12 tháng. Sau 3 tháng làm việc, anh A xin nghỉ việc và thông báo trước 2 ngày. Hỏi: Anh A có vi phạm quy định pháp luật không?", a: "Có, vì anh A phải thông báo trước ít nhất 30 ngày." },
  { id: 348, subject: "bai9", q: "Công ty Y sa thải anh C vì thường xuyên đi làm muộn và không hoàn thành công việc. Công ty đã không tổ chức họp xử lý kỷ luật và không thông báo trước cho anh C. Hỏi: Công ty có vi phạm pháp luật không?", a: "Có, vì công ty chưa tổ chức họp xử lý kỷ luật theo quy định." },
  { id: 349, subject: "bai9", q: "Chị E xin nghỉ việc 3 ngày để dự đám cưới em gái. Công ty từ chối không cho nghỉ. Hỏi: Công ty có vi phạm quy định pháp luật không?", a: "Không, vì việc nghỉ cưới em gái không thuộc trường hợp nghỉ có hưởng lương." },
  { id: 350, subject: "bai9", q: "Anh F được tuyển dụng vào vị trí chuyên viên tại công ty N và phải thử việc trong 3 tháng. Hỏi: Thời gian thử việc này có phù hợp quy định pháp luật không?", a: "Không, vì thời gian thử việc tối đa chỉ là 60 ngày." },
  { id: 351, subject: "bai9", q: "Công ty Y yêu cầu chị G chuyển sang làm một công việc khác không đúng với hợp đồng lao động trong thời gian 1 tháng. Công ty đã thông báo trước và mức lương của chị G không thay đổi. Hỏi: Công ty Y có vi phạm quy định pháp luật không?", a: "Có, vì công ty không được phép thay đổi công việc đã ký kết" },
  { id: 352, subject: "bai9", q: "Người lao động tại công ty Z tổ chức đình công vì cho rằng công ty trả lương không đúng như cam kết. Họ chưa tiến hành hòa giải và không lấy ý kiến tập thể trước khi đình công. Hỏi: Cuộc đình công này có hợp pháp không?", a: "Không, vì người lao động không lấy ý kiến trước khi đình công và chưa tiến hành hòa giải." },
  { id: 353, subject: "bai9", q: "Anh H làm việc tại công ty P được 3 tháng và xin nghỉ phép năm 2 ngày. Hỏi: Anh H có được quyền nghỉ phép năm trong trường hợp này không?", a: "Có, nếu công ty đồng ý cho phép anh H được nghỉ phép tạm ứng." },
  { id: 354, subject: "bai9", q: "Anh A ký hợp đồng lao động không xác định thời hạn với công ty X. Sau một thời gian, anh A không còn muốn tiếp tục công việc vì lý do cá nhân và thông báo nghỉ việc ngay lập tức. Theo quy định pháp luật, hành vi của anh A có đúng không? Nếu sai, anh A cần làm gì để nghỉ việc hợp pháp?", a: "Thông báo nghỉ ngay là sai, anh A phải báo trước ít nhất 45 ngày." },
  { id: 355, subject: "bai9", q: "Ông E làm việc tại một doanh nghiệp tư nhân và bị tai nạn lao động trong quá trình làm việc. Tuy nhiên, doanh nghiệp từ chối bồi thường với lý do tai nạn không nghiêm trọng. Hãy giải thích quyền lợi của ông E trong trường hợp này.", a: "Ông E có quyền yêu cầu bồi thường nếu tai nạn xảy ra trong giờ làm việc." },
  { id: 356, subject: "bai9", q: "Một lao động nữ đang mang thai 5 tháng bị công ty chấm dứt hợp đồng lao động với lý do giảm biên chế. Hành động của công ty có vi phạm pháp luật không?", a: "Có, vì luật cấm chấm dứt hợp đồng với lao động nữ đang mang thai." },
  { id: 357, subject: "bai9", q: "Anh G ký hợp đồng lao động có thời hạn 12 tháng. Sau khi hết hạn hợp đồng, anh tiếp tục làm việc mà không ký hợp đồng mới. Trong trường hợp này, hợp đồng của anh G được xem là loại hợp đồng nào?", a: "Hợp đồng lao động không xác định thời hạn." },
  { id: 358, subject: "bai9", q: "Chị H làm việc tại một công ty thời hạn 24 tháng nhưng không được công ty đóng bảo hiểm xã hội. Khi chị khiếu nại, công ty cho rằng đó là thỏa thuận riêng giữa hai bên. Hãy phân tích tính hợp pháp trong trường hợp này.", a: "Không hợp pháp, vì việc đóng bảo hiểm xã hội là bắt buộc." },
  { id: 359, subject: "bai9", q: "Chị L xin nghỉ việc để chăm sóc người thân bị ốm và đề nghị công ty cho nghỉ không lương trong 1 tháng. Công ty từ chối vì lý do công việc bận rộn. Quyết định của công ty có hợp pháp không?", a: "Hợp pháp, nếu công ty có lý do chính đáng." },
  { id: 360, subject: "bai9", q: "Anh B làm việc tại công ty Y và ký hợp đồng lao động không xác định thời hạn. Trong thời gian nghỉ phép năm, công ty ra quyết định kỷ luật sa thải anh B vì lỗi nghiêm trọng xảy ra trước đó. Quyết định này có đúng luật không?", a: "Sai, vì không thể sa thải người lao động trong thời gian nghỉ phép." },
];
